# fly.toml app configuration file generated for app-skripsiku on 2024-01-09T15:07:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "app-skripsiku"
primary_region = "sin"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
